name: Lint Codebase

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  symlinks:
    name: Consolidate Inventory Symlinks
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write
      pull-requests: write

    steps:
      - name: Generate GitHub token
        id: token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          # token: ${{ steps.token.outputs.token }}
          persist-credentials: false

      - name: Setup GitHub CLI authentication
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: gh auth setup-git

      # - name: Checkout code
      #   uses: actions/checkout@v6
      #   with:
      #     ref: ${{ github.ref }}
      #     # token: ${{ steps.token.outputs.token }}
      #     persist-credentials: false


      - name: Checkout PR branch
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - run: git log --oneline

      - run: echo "${{ github.run_id }}" >> text.txt

      - name: "Commit changes back to PR"
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: |
          git config --global user.name "ama-pfs-america-ansible-automation[bot]"
          git config --global user.email "265116361+ama-pfs-america-ansible-automation[bot]@users.noreply.github.com"
          git add --all . 
          git commit -m "Automated symlink consolidation [skip ci]" 
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.event.pull_request.head.repo.full_name }}.git 
          git push origin HEAD:${{ github.event.pull_request.head.ref }}

