name: test_something

on:
  workflow_dispatch: :

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  symlinks:
    name: Consolidate Inventory Symlinks
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write
      pull-requests: write

    steps:
      - name: Generate GitHub token
        id: token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
